[package]
name = "crm-common"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
itertools = "0.13.0"
sqlx = { workspace = true }
tokio = { workspace = true }
uuid = { version = "1.10.0", features = ["v4"] }
